### ISSUE TITLE
toster_dirty is not defined

### ISSUE THREAD

**Issue by krzys-h** [warsztatywww/TosterBot#9]
broken probably after #4 
```
toster_1  | Ignoring exception in on_message
toster_1  | Traceback (most recent call last):
toster_1  |   File "/usr/local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
toster_1  |     await coro(*args, **kwargs)
toster_1  |   File "toster.py", line 123, in on_message
toster_1  |     if toster_dirty >= DIRTY_THRESHOLD:
toster_1  | NameError: name 'toster_dirty' is not defined
```

**Comment by enedil** [comment]
I think it's resolved
